'use strict';
// A deterministic DOM adapter exercises the real app event handlers without a network/browser dependency.
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),crypto=require('node:crypto');
const C=require('../easyread/web/mobile/core.js'),O=require('../easyread/web/js/common/organization.js');
const elements=new Map(),listeners={},checkInputs=[];
function element(id){if(elements.has(id))return elements.get(id);const e={id,value:'',checked:false,disabled:false,hidden:false,open:false,dataset:{},events:{},textContent:'',classList:{toggle(){}},setAttribute(){},getAttribute(){},addEventListener(n,fn){this.events[n]=fn;},showModal(){this.open=true;},close(){this.open=false;this.events.close?.();},click(){return this.onclick?.({target:this});},querySelector(){return null;},querySelectorAll(){return [];},focus(){},remove(){},append(){}};Object.defineProperty(e,'innerHTML',{get(){return this._html||'';},set(html){this._html=html;parse(html);}});elements.set(id,e);return e;}
function parse(html){for(const m of html.matchAll(/<(input|select|button|p|section|div|textarea|h\d|details|label)\b([^>]*)>/g)){const attrs=m[2],id=attrs.match(/\bid="([^"]+)"/)?.[1];if(!id)continue;const e=element(id);e.value=attrs.match(/\bvalue="([^"]*)"/)?.[1]||'';e.checked=/\bchecked\b/.test(attrs);e.disabled=/\bdisabled\b/.test(attrs);e.hidden=/\bhidden\b/.test(attrs);if(m[1]==='select'){const rest=html.slice(m.index+m[0].length).split('</select>')[0];const options=[...rest.matchAll(/<option\b([^>]*)>/g)];e.value=(options.find(o=>/\bselected\b/.test(o[1]))||options[0])?.[1].match(/\bvalue="([^"]*)"/)?.[1]||'';}}
if(html.includes('name="classifyPaper"')){checkInputs.length=0;for(const m of html.matchAll(/<input\b([^>]*)name="classifyPaper"([^>]*)>/g)){const attrs=m[1]+m[2];checkInputs.push({value:attrs.match(/\bvalue="([^"]*)"/)[1],checked:/\bchecked\b/.test(attrs)});}}}
for(const id of ['app','sheet','sheetBody','sheetTitle','sheetClose','toast','tabs','headerStatus','importButton','importFile','selectionTools','selectionNote','selectionCancel','home','themeMeta'])element(id);
const document={querySelector:s=>s==='meta[name="theme-color"]'?element('themeMeta'):elements.get(s.slice(1))||null,querySelectorAll:s=>s==='[name="classifyPaper"]:checked'?checkInputs.filter(e=>e.checked):[],addEventListener:(n,fn)=>{listeners[n]=fn;},documentElement:{dataset:{},style:{setProperty(){}}},body:{classList:{toggle(){}},append(){}},hidden:false};
const papers=new Map(),prefs=new Map([['aiOptions',{base_url:'https://model.example',model:'test-model',remember_key:true}],['aiKey','device-only']]);
const fixture=C.normalize({paper_id:'p1',paper:{meta:{title_en:'Forests',authors:'A'},blocks:[{id:'intro',type:'para',en:'forest evidence'}]},reader:C.emptyReader(),item:{tags:[]}});papers.set('p1',fixture);
let delaySave=false,releaseSave=null;
let org=O.seed(O.empty(),[fixture]),mutations=0,requests=0,resolveFetch=null;
const S={indexes:async()=>[],all:async()=>[...papers.values()],get:async id=>papers.get(id),organization:async()=>org,changeOrganization:async fn=>{if(delaySave)await new Promise(resolve=>{releaseSave=resolve;});const next=fn(org);org=next;mutations++;return org;},setting:async(k,v)=>v===undefined?prefs.get(k):prefs.set(k,v),save:async p=>papers.set(p.paper_id,p),update:async(id,fn)=>{const p=papers.get(id);fn(p);return p;},source:async()=>null,importBundle:async p=>{if(!papers.has(p.paper_id))papers.set(p.paper_id,p);return papers.get(p.paper_id);}};
const D={connected:false,syncing:false,lastImportReport:null,account:null};
const window={FolioMobile:C,FolioOrganization:O,FolioStorage:S,FolioDrive:D,FolioPlatform:{native:true,bundledAssets:true},FolioPDF:{MAX_SOURCE:128*1024*1024,sha:async()=> 'p1',parse:async()=>{throw new Error('Duplicate PDF must not parse');}},FolioJournal:{badges:()=>'',visible:()=>false},scrollTo(){},addEventListener(){}};
const context={window,document,crypto,URL,Set,Map,Promise,AbortController,TextEncoder,Blob,Date,console,navigator:{onLine:false},matchMedia:()=>({matches:false,addEventListener(){}}),getSelection:()=>({removeAllRanges(){},isCollapsed:true}),setTimeout:()=>0,clearTimeout(){},setInterval(){},requestAnimationFrame(){},PR:{md:x=>x,citationReferences:[],refById:{}},fetch:async(url,options)=>{if(url==='./config.json')return Response.json({});requests++;return new Promise(resolve=>{resolveFetch=()=>resolve(Response.json({choices:[{message:{content:JSON.stringify({suggestions:[{paper_id:'p1',folder_id:null,folder_name:'Suggested',tags:['forest']}]})}}]}));});}};
vm.runInNewContext(fs.readFileSync('easyread/web/mobile/ai.js','utf8'),context);vm.runInNewContext(fs.readFileSync('easyread/web/mobile/app.js','utf8'),context);
const flush=async()=>{for(let i=0;i<5;i++)await new Promise(setImmediate);};
async function action(dataset,selector='[data-act]'){await listeners.click({target:{closest:s=>s===selector?{dataset}:null},preventDefault(){}});await flush();}
const click=async id=>{await element(id).onclick({target:element(id)});await flush();};
async function preview(){await action({act:'classifyPapers'});await click('previewClassification');}
(async()=>{await flush();assert(element('app').innerHTML.includes('管理文件夹'));
await action({act:'manageFolders'});element('folderName').value='Empty';await click('addFolder');const folder=O.live(org)[0].id;assert(folder);assert.equal(requests,0);
await action({organizePaper:'p1'},'[data-organize-paper]');element('paperFolder').value=folder;element('paperTags').value='A, B';await click('savePaperOrganization');assert.equal(org.assignments.p1.folder_id,folder);assert.deepEqual(org.assignments.p1.tags,['A','B']);
await action({act:'manageFolders'});element('folderName').value='Different destination';await click('addFolder');const alternate=O.live(org).find(f=>f.name==='Different destination').id;
await action({act:'import'});assert(element('sheetBody').innerHTML.includes('目标文件夹'));element('importFolder').value=alternate;element('importTags').value='imported';await click('chooseImport');assert.equal(requests,0);assert.equal(papers.size,1,'Opening or cancelling import never creates another paper');
const beforeDuplicate=O.canonical(org);await element('importFile').onchange({target:{files:[{name:'duplicate.pdf',type:'application/pdf',size:8,arrayBuffer:async()=>new Uint8Array([1,2,3]).buffer}],value:'duplicate.pdf'}});await flush();assert.equal(O.canonical(org),beforeDuplicate,'Duplicate PDF must not move or add import tags');assert.equal(papers.size,1);await action({act:'library'});
await preview();assert.equal(requests,0);assert.equal(element('classificationConsent').checked,false);assert.equal(element('requestClassification').disabled,true);assert(element('sheetBody').innerHTML.includes('https://model.example/chat/completions'));assert(element('sheetBody').innerHTML.includes('test-model'));assert(element('sheetBody').innerHTML.includes('forest evidence'));
// The real handler refuses even direct synthetic calls without opt-in.
await click('requestClassification');assert.equal(requests,0);
element('classificationConsent').checked=true;element('classificationConsent').onchange({target:element('classificationConsent')});
const request=element('requestClassification').onclick();await flush();const duplicate=element('requestClassification').onclick();await flush();assert.equal(requests,1,'Repeated click creates one request');
const before=O.canonical(org);window.FolioPlatform.onBack();assert.equal(element('sheet').open,false);resolveFetch();await request;await duplicate;await flush();assert.equal(O.canonical(org),before,'Android Back cancels; late response cannot apply or reopen');assert.equal(element('sheet').open,false);
await preview();element('classificationConsent').checked=true;const reviewRequest=element('requestClassification').onclick();await flush();resolveFetch();await reviewRequest;await flush();assert.equal(O.canonical(org),before,'Review never auto-applies');assert(element('sheetBody').innerHTML.includes('检查')||element('sheetTitle').textContent.includes('检查'));element('reviewNewFolder0').value='Edited';element('reviewTags0').value='verified, topic';
const previousMutations=mutations,apply=element('applyClassification').onclick(),repeat=element('applyClassification').onclick();await apply;await repeat;await flush();assert.equal(mutations,previousMutations+1);assert.equal(org.folders[org.assignments.p1.folder_id].name,'Edited');assert.deepEqual(org.assignments.p1.tags,['verified','topic']);assert.equal(papers.size,1);
// Confirming authorizes the save, but closing while IndexedDB is pending must not dismiss a newer dialog.
await preview();element('classificationConsent').checked=true;const delayedReview=element('requestClassification').onclick();await flush();resolveFetch();await delayedReview;await flush();delaySave=true;const pendingApply=element('applyClassification').onclick();await flush();window.FolioPlatform.onBack();await action({act:'manageFolders'});assert.equal(element('sheetTitle').textContent,'管理文献文件夹');releaseSave();await pendingApply;await flush();delaySave=false;assert.equal(element('sheet').open,true);assert.equal(element('sheetTitle').textContent,'管理文献文件夹','A completed earlier save cannot close the newer sheet');
await action({deleteFolder:folder},'[data-delete-folder]');await click('confirmDeleteFolder');assert.equal(org.folders[folder].deleted,true);assert.equal(papers.size,1);
console.log('Mobile UI handlers: manual folders/tags/import preview, explicit AI consent, duplicate sends/apply, review edits, cancel/late response and Android Back passed');
})().catch(e=>{console.error(e);process.exitCode=1;});
