'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),crypto=require('node:crypto');
const O=require('../easyread/web/js/common/organization.js'),C=require('../easyread/web/mobile/core.js');
const v=(at,id)=>({at,id});
let base=O.createFolder(O.empty(),'森林',v('2026-01-01T00:00:00.000Z','a'));const folder=O.live(base)[0].id;
base=O.assign(base,[{paper_id:'paper',folder_id:folder,tags:['Satellite','satellite','森林']}],v('2026-01-02T00:00:00.000Z','b'));
assert.deepEqual(base.assignments.paper.tags,['Satellite','森林']);
const renamed=O.renameFolder(base,folder,'遥感',v('2026-01-03T00:00:00.000Z','c'));
assert.equal(O.live(renamed)[0].id,folder);assert.equal(O.assignment(renamed,'paper').folder_id,folder);
const removed=O.deleteFolder(base,folder,v('2026-01-02T00:00:00.000Z','d'));
assert.equal(O.assignment(O.merge(removed,renamed),'paper').folder_id,null,'Remove wins against later concurrent rename');
assert.deepEqual(O.merge(removed,renamed),O.merge(renamed,removed));
assert.equal(O.merge(removed,renamed).assignments.paper.tags[0],'Satellite');
assert.equal(O.live(O.merge(O.empty(),O.createFolder(base,'空文件夹'))).length,2,'Empty folders retained');
assert.throws(()=>O.createFolder(base,' 森林 '),/同名/);
const legacy=O.seed({},[{paper_id:'legacy',item:{tags:Array.from({length:20},(_,i)=>'x'.repeat(80)+i)}}]);assert.equal(legacy.assignments.legacy.tags.length,20);
assert.equal(O.seed(base,[{paper_id:'paper',item:{tags:['stale']}}]).assignments.paper.tags[0],'Satellite');
assert.throws(()=>O.assign(base,[{paper_id:'paper',tags:['changed'],expected_version:{at:'',id:''}}]),/已在其他/);
assert.throws(()=>O.tags(['x'.repeat(41)],true),/40/);
assert.equal(O.assign(base,[{paper_id:'paper',tags:Array.from({length:20},(_,i)=>'legacy'+i)}]).assignments.paper.tags.length,20,'Manual organization retains legacy-sized tag sets');
assert.throws(()=>O.assign(base,[{paper_id:'paper',tags:['bad\u0000tag']}]),/控制/);
const atomic=O.assign(base,[{paper_id:'paper',folder_name:'New',tags:['A']},{paper_id:'paper2',folder_name:'new',tags:['B']}]);assert.equal(atomic.assignments.paper.folder_id,atomic.assignments.paper2.folder_id);
assert.equal(Object.keys(base.folders).length,1,'Input never mutated');
assert.throws(()=>O.assign(base,[{paper_id:'paper',folder_name:'Valid',tags:[]},{paper_id:'other',folder_id:'missing',tags:[]}]),/已删除/);assert.equal(Object.keys(base.folders).length,1);
const malicious=JSON.parse('{"folders":{"__proto__":{"name":"evil"}},"assignments":{"constructor":{"tags":["bad"]}}}');assert.deepEqual(O.normalize(malicious),O.empty());
const paper=C.normalize({paper_id:'paper',paper:{meta:{title_en:'Remote sensing',abstract_en:'Abstract'},blocks:[{id:'a',type:'para',en:'Evidence only'}]},item:{tags:['old']},reader:C.emptyReader(),organization:base});
const isolated=C.normalize({...paper,organization:O.createFolder(base,'Private unrelated folder')});assert.equal(Object.keys(isolated.organization.folders).length,1);assert(!JSON.stringify(isolated).includes('Private unrelated folder'));
assert.deepEqual(paper.item.tags,base.assignments.paper.tags);assert.equal(paper.organization.assignments.paper.folder_id,folder);
assert.equal(C.normalize({...paper,organization:undefined}).organization,undefined);
let requests=0,response={suggestions:[{paper_id:'paper',folder_id:folder,folder_name:'',tags:['Review']}]};
const window={FolioOrganization:O};
vm.runInNewContext(fs.readFileSync('easyread/web/mobile/ai.js','utf8'),{window,URL,Set,fetch:async(url,options)=>{requests++;assert.equal(options.redirect,'error','Disclosed model endpoint cannot redirect text to another host');assert.equal(url,'https://model.example/chat/completions');assert(!options.body.includes('device-secret'));return Response.json({choices:[{message:{content:JSON.stringify(response)}}]});}});
(async()=>{const A=window.FolioAI;A.setConfig({base_url:'https://model.example',model:'custom-model',api_key:'device-secret'});
const preview=A.classificationPreview([paper],base);const bounded=A.classificationPreview([{...paper,paper:{meta:{title_en:'T'.repeat(350)},blocks:[{id:'abstract',role:'abstract',en:'A'.repeat(2200)},...Array.from({length:8},(_,i)=>({id:'b'+i,en:'B'.repeat(1200)}))]}}],base);const boundedText=JSON.parse(bounded.messages[1].content).papers[0];assert.equal(boundedText.title.length,300);assert.equal(boundedText.abstract.length,2000);assert.equal(boundedText.excerpt.length,3000);
assert.equal(requests,0);assert.equal(preview.provider,'model.example');assert.equal(preview.model,'custom-model');assert(preview.messages[1].content.includes('Evidence only'));assert(!JSON.stringify(preview).includes('device-secret'));
await assert.rejects(A.classify(preview),/明确同意/);assert.equal(requests,0);
const suggestions=await A.classify(preview,{consent:true});assert.equal(suggestions[0].tags[0],'Review');assert.equal(base.assignments.paper.tags[0],'Satellite','AI response never applies itself');
assert.equal(preview.allow_new_folders,false);assert.match(preview.messages[0].content,/0–4/);assert.match(preview.messages[0].content,/不要凑满/);assert(preview.existing_tags.includes('Satellite'));
response={suggestions:[{paper_id:'paper',folder_id:null,folder_name:'Invented topic',tags:['satellite','A','B','C','D','E']}]};
let compact=await A.classify(preview,{consent:true});assert.deepEqual(Array.from(compact[0].tags),['Satellite','A','B','C']);assert.equal(compact[0].folder_id,folder);assert.equal(compact[0].folder_name,'');
response={suggestions:[{paper_id:'paper',folder_id:null,folder_name:'森林',tags:[]}]};compact=await A.classify(preview,{consent:true});assert.equal(compact[0].folder_id,folder);assert.equal(compact[0].tags.length,0,'No tag quota to fill');
response={suggestions:[{paper_id:'paper',folder_id:null,folder_name:'New topic',tags:['one']}]};compact=await A.classify(A.classificationPreview([paper],base,{allow_new_folders:true}),{consent:true});assert.equal(compact[0].folder_name,'New topic');assert.equal(compact[0].tags.length,1);
const batch=A.classificationPreview([paper,{...paper,paper_id:'paper2'}],base,{allow_new_folders:true});response={suggestions:[{paper_id:'paper',folder_name:'First',tags:[]},{paper_id:'paper2',folder_name:'Second',tags:[]}]};await assert.rejects(A.classify(batch,{consent:true}),/最多建议 1/);
response={suggestions:[{paper_id:'intruder',tags:[]}]};await assert.rejects(A.classify(preview,{consent:true}),/标识/);
const controller=new AbortController();controller.abort();const before=requests;await assert.rejects(A.classify(preview,{consent:true,signal:controller.signal}),/取消/);assert.equal(requests,before);
A.setConfig({model:'changed'});await assert.rejects(A.classify(preview,{consent:true}),/配置已变化/);assert.equal(requests,before);
console.log('Organization: stable folders, tags, remove-wins, deterministic merge, legacy preservation, atomic/stale-safe assignments, portable privacy, exact AI disclosure/opt-in/cancellation passed');
})().catch(e=>{console.error(e);process.exitCode=1;});
