const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const citations=require('../easyread/web/js/common/citations.js');
const J=require('../easyread/web/js/common/journal-rank.js');
const C=require('../easyread/web/mobile/core.js');
const refs=[{id:'1',text:'John Smith, A. Jones. Title. Journal A, 2023. doi:10.1234/test.'},{id:'2',text:'Rafailov, R., A. Sharma. Direct preference optimization. 2023.'},{id:'3',text:'Smith, J. A different paper. 2023.'},{id:'4',text:'Smith, J. Another paper. 2023a.'}];
const context={PR:{esc:C.esc,refById:Object.fromEntries(refs.map(r=>[r.id,r])),citationReferences:refs},FolioCitations:citations,katex:{renderToString:t=>'<math>'+C.esc(t)+'</math>'},URL};context.window=context;
vm.createContext(context);vm.runInContext(fs.readFileSync('easyread/web/js/common/markup.js','utf8'),context);
const md=context.PR.md;
assert.match(md('资料 [1–3, 4]'),/data-refs="1\|2\|3\|4"/);
assert.match(md('Rafailov et al. (2023)'),/data-refs="2"/);
assert.match(md('（Rafailov 等, 2023；Smith, 2023a）'),/data-refs="4"/);
assert.match(md('(Smith et al., 2023)'),/data-refs="1\|3" data-cite-ambiguous="true"/);
assert.equal(md('[7] 数据 (2023) 公式 (1)'), '[7] 数据 (2023) 公式 (1)');
assert.doesNotMatch(md('`[1]` $[1]$'),/class="cite"/);
assert.doesNotMatch(md('[1](https://example.org/x) https://example.org/[2]'),/class="cite"/);
assert.doesNotMatch(md('[1]',{cite:false}),/class="cite"/);
assert.doesNotMatch(md('<img src=x onerror=alert(1)> [1]'),/<img/);
assert.match(md('[1]'),/href="#ref-1"/);
const rank={source:'easyScholar',publication:'Journal A',queried_at:'2026-10-03T01:00:00Z',metrics:[{key:'sci',value:'Q1',secret_key:'private'}],secret_key:'private',raw:{token:'private'}};
const normalized=C.normalize({paper_id:'paper-one',paper:{meta:{journal_rank:rank},blocks:[]}});
assert.doesNotMatch(JSON.stringify(normalized),/private/);
assert.match(J.badges({venue:'Journal A',journal_rank:rank}),/Q1/);
assert.equal(J.badges({venue:'Journal B',journal_rank:rank}),'');
assert.doesNotMatch(J.details({venue:'Journal A',journal_rank:{...rank,metrics:[{key:'sci',value:'<img onerror=x>'}]}}),/<img/);
console.log('Citation matching, safe links and portable journal metadata passed');
