"""翻译 / 对话引擎的 API 预设：服务商、地址、推荐模型。"""

# 常见的 OpenAI 兼容服务。group：local 本机开源模型 / free 有免费模型或免费额度 / paid 付费。
# models 是推荐的模型名（设置页里可选，也能手填）。模型名和免费政策会变，以服务商页面为准。
PRESETS = [
    {"id": "llamacpp", "group": "local", "name": "llama.cpp / DFlash", "base_url": "http://127.0.0.1:8080/v1", "model": "qwen3.8-27b-q6k-dflash2", "key": False,
     "models": ["qwen3.8-27b-q6k-dflash2"], "vision": True, "reasoning_effort": "none",
     "note": "连接已启动的本机 llama.cpp 服务。模型名以服务的 /v1/models 为准；翻译默认关闭深度思考，单批逐页处理。"},
    {"id": "ollama", "group": "local", "name": "Ollama", "base_url": "http://127.0.0.1:11434/v1", "model": "qwen3:8b", "key": False,
     "models": ["qwen3:8b", "qwen3:14b", "qwen2.5:14b", "glm4:9b", "gemma3:12b", "deepseek-r1:8b"],
     "key_url": "https://ollama.com/download", "note": "装好 Ollama，再 ollama pull qwen3:8b。完全离线、免费；8B 模型要 8 GB 左右显存，14B 译得更好。"},
    {"id": "lmstudio", "group": "local", "name": "LM Studio", "base_url": "http://127.0.0.1:1234/v1", "model": "qwen/qwen3-8b", "key": False,
     "models": ["qwen/qwen3-8b", "qwen/qwen3-14b", "google/gemma-3-12b"],
     "key_url": "https://lmstudio.ai", "note": "在 LM Studio 里下载模型，打开 Developer → Start Server。"},
    {"id": "zhipu", "group": "free", "name": "智谱 GLM", "base_url": "https://open.bigmodel.cn/api/paas/v4", "model": "glm-4.5-flash", "key": True,
     "models": ["glm-4.5-flash", "glm-4-flash-250414", "glm-4.5-air", "glm-4.5"],
     "key_url": "https://open.bigmodel.cn/usercenter/apikeys", "note": "glm-4.5-flash、glm-4-flash 免费；GLM 系列权重开源。"},
    {"id": "siliconflow", "group": "free", "name": "硅基流动", "base_url": "https://api.siliconflow.cn/v1", "model": "Qwen/Qwen3-8B", "key": True,
     "models": ["Qwen/Qwen3-8B", "THUDM/GLM-4-9B-0414", "Qwen/Qwen2.5-7B-Instruct", "Qwen/Qwen3-32B", "deepseek-ai/DeepSeek-V3", "Qwen/Qwen2.5-VL-72B-Instruct"],
     "key_url": "https://cloud.siliconflow.cn/account/ak", "note": "托管开源模型：Qwen3-8B、GLM-4-9B 等 8B 级免费；更大的模型付费。"},
    {"id": "modelscope", "group": "free", "name": "魔搭 ModelScope", "base_url": "https://api-inference.modelscope.cn/v1", "model": "Qwen/Qwen3-32B", "key": True,
     "models": ["Qwen/Qwen3-32B", "Qwen/Qwen3-235B-A22B", "deepseek-ai/DeepSeek-V3", "ZhipuAI/GLM-4.5"],
     "key_url": "https://modelscope.cn/my/myaccesstoken", "note": "阿里的开源模型社区，开源模型每天有免费调用次数（需绑定阿里云账号）。"},
    {"id": "groq", "group": "free", "name": "Groq", "base_url": "https://api.groq.com/openai/v1", "model": "llama-3.3-70b-versatile", "key": True,
     "models": ["llama-3.3-70b-versatile", "qwen/qwen3-32b", "openai/gpt-oss-120b"],
     "key_url": "https://console.groq.com/keys", "note": "开源模型、免费额度、速度很快；有每分钟频率限制，并发开 1–2。"},
    {"id": "cerebras", "group": "free", "name": "Cerebras", "base_url": "https://api.cerebras.ai/v1", "model": "qwen-3-32b", "key": True,
     "models": ["qwen-3-32b", "llama-3.3-70b", "gpt-oss-120b"],
     "key_url": "https://cloud.cerebras.ai", "note": "开源模型、免费额度。"},
    {"id": "github", "group": "free", "name": "GitHub Models", "base_url": "https://models.github.ai/inference", "model": "openai/gpt-4.1-mini", "key": True,
     "models": ["openai/gpt-4.1-mini", "openai/gpt-4.1", "deepseek/DeepSeek-V3-0324", "meta/Llama-4-Maverick-17B-128E-Instruct-FP8"],
     "key_url": "https://github.com/settings/tokens", "note": "用 GitHub 账号的 token（勾 models 权限）即可免费调用，每天有次数限制。"},
    {"id": "gemini", "group": "free", "name": "Google Gemini", "base_url": "https://generativelanguage.googleapis.com/v1beta/openai", "model": "gemini-2.5-flash", "key": True,
     "models": ["gemini-2.5-flash", "gemini-2.5-flash-lite", "gemini-2.5-pro"],
     "key_url": "https://aistudio.google.com/apikey", "note": "免费额度，能看图（建议勾选“模型能看图”）。需要能访问 Google。"},
    {"id": "openrouter", "group": "free", "name": "OpenRouter", "base_url": "https://openrouter.ai/api/v1", "model": "deepseek/deepseek-chat-v3-0324:free", "key": True,
     "models": ["deepseek/deepseek-chat-v3-0324:free", "qwen/qwen3-235b-a22b:free", "meta-llama/llama-3.3-70b-instruct:free"],
     "key_url": "https://openrouter.ai/keys", "note": "带 :free 后缀的开源模型免费，有频率限制。"},
    {"id": "deepseek", "group": "paid", "name": "DeepSeek", "base_url": "https://api.deepseek.com/v1", "model": "deepseek-chat", "key": True,
     "models": ["deepseek-chat", "deepseek-reasoner"],
     "key_url": "https://platform.deepseek.com/api_keys", "note": "开源模型的官方接口，很便宜，一篇 20 页论文大约几毛钱。"},
    {"id": "dashscope", "group": "paid", "name": "通义千问", "base_url": "https://dashscope.aliyuncs.com/compatible-mode/v1", "model": "qwen-plus", "key": True,
     "models": ["qwen-plus", "qwen-max", "qwen-turbo", "qwen-vl-max"],
     "key_url": "https://bailian.console.aliyun.com/?apiKey=1", "note": "阿里云百炼，新用户有免费额度；qwen-vl-max 能看图。"},
    {"id": "moonshot", "group": "paid", "name": "Kimi", "base_url": "https://api.moonshot.cn/v1", "model": "kimi-k2-0905-preview", "key": True,
     "models": ["kimi-k2-0905-preview", "moonshot-v1-32k"], "key_url": "https://platform.moonshot.cn/console/api-keys", "note": ""},
    {"id": "openai", "group": "paid", "name": "OpenAI", "base_url": "https://api.openai.com/v1", "model": "gpt-4.1-mini", "key": True,
     "models": ["gpt-4.1-mini", "gpt-4.1", "gpt-5-mini", "gpt-5"], "key_url": "https://platform.openai.com/api-keys", "note": "能看图。"},
    {"id": "anthropic", "group": "paid", "name": "Anthropic（Claude）", "base_url": "https://api.anthropic.com/v1", "model": "claude-sonnet-5-5", "key": True,
     "models": ["claude-sonnet-5-5", "claude-opus-5-5", "claude-haiku-4-5"], "key_url": "https://console.anthropic.com/settings/keys",
     "note": "Anthropic 的 OpenAI 兼容接口；能看图。"},
]
PRESET_GROUPS = [("local", "本机运行（开源、免费、离线）"), ("free", "有免费模型或免费额度"), ("paid", "付费（便宜、译得好）")]
